### ISSUE TITLE
Why markdown and not HTML?

### ISSUE THREAD

**Issue by averydelmiller** [McFlat/peertube-plugin-custom-links#2]
Hello! Hope all is well.
I was curious why markdown is used instead of plain HTML. (I assume it's to prevent messing something up, but it would allow to add external links that have the same style as the buttons in the top menu, which would be awesome for linking to Patreon or social accounts.) I've tried a couple different things, like using javascript to add html into the custom links div, but I haven't had much luck.

**Comment by chrisspiegl** [comment]
Same, don't think the way it is implemented right now is very helpful since it does not match the look of the page very well.

**Comment by chrisspiegl** [comment]
I did some custom styling and it looks kind of decent to pass as a normal menu link. It even looks decent when you have multiple sections (sections are marked by doing a bold text line with `**SECTION**`).

<img width="254" alt="Screen Shot 2021-05-28 at 08 41 02" src="https://user-images.githubusercontent.com/1096384/119941109-71c71380-bf90-11eb-9b14-cfc0f366dc17.png">

**Markdown in Custom Links Settings**

```md
**OTHER LINKS**
[Main Website](https://ChrisSpiegl.com)
[Patron / Support](https://ChrisSpiegl.com/support)
[YouTube](https://youtube.com/ChrisSpiegl)
[Discord Server](https://crsp.li/discord)
```

**CSS in Configuration > Advanced > Custom CSS**

```css
#custom-css .custom-links {
    margin-bottom: 15px;
}

#custom-css .custom-links br {
    display: none;
}

#custom-css .custom-links strong {
    display: block;
    margin-bottom: 15px;
    margin-top: 34px;
    text-transform: uppercase;
    font-weight: 700;
    font-size: 13px;
    margin-left: 26px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    margin-right: 30px;
}

#custom-css .custom-links a {   
    display: flex;
    align-items: center;
    padding-left: 26px;
    color: var(--menuForegroundColor);
    cursor: pointer;
    font-size: 16px;
    white-space: normal;
    word-break: break-word;
    padding-right: 20px;
    transition: background-color .1s ease-in-out;
    line-height: 1.2;
    min-height: 40px;
}
```
